FROM --platform=arm64 node:24-alpine AS base

WORKDIR /app

RUN npm install -g pnpm

FROM base AS pruner

COPY . .
RUN pnpm dlx turbo prune ws --docker

FROM base AS installer

COPY --from=pruner /app/out/json .
COPY --from=pruner /app/out/pnpm-lock.yaml ./pnpm-lock.yaml

RUN pnpm install --frozen-lockfile

FROM base AS runner

COPY --from=pruner /app/out/full .
COPY --from=installer /app/node_modules ./node_modules
COPY --from=installer /app/apps ./apps

COPY --from=installer /app/packages ./packages

WORKDIR /app/packages/db
ENV DATABASE_URL="postgres://saket:n3rd@localhost:5434/mydb"
RUN pnpm exec prisma generate

WORKDIR /app
RUN pnpm --filter=@repo/db build || true

EXPOSE 8080

CMD ["pnpm", "--filter", "ws", "dev"]